# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwpastebin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paste',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
