# Generated by Django 3.0.3 on 2020-02-29 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kwpastebin', '0005_auto_20200218_2001'),
        ('kwpastebin', '0004_auto_20190727_1318'),
    ]

    operations = [
    ]
